export async function GET(request){
 const origin=new URL(request.url).origin;
 const script=`(()=>{const s=document.currentScript;if(!s||s.dataset.eonMounted)return;s.dataset.eonMounted='true';const k=s.dataset.workspace,p=s.dataset.product,v=s.dataset.variant,c=s.dataset.currency,surface=s.dataset.surface||'product';if(!k||!p||!v||!c)return;
 const started=Date.now();let visits=1,visitor=crypto.randomUUID(),testerToken='',invite=null,pending=false,closed=false;
 try{const key='eon-visits:'+k+':'+v;visits=Math.min(100,Number(localStorage.getItem(key)||0)+1);localStorage.setItem(key,String(visits));visitor=localStorage.getItem('eon-visitor:'+k)||visitor;localStorage.setItem('eon-visitor:'+k,visitor);
 const hash=new URLSearchParams(location.hash.slice(1));testerToken=hash.get('eonTest')||sessionStorage.getItem('eon-test:'+k)||'';if(hash.has('eonTest')){sessionStorage.setItem('eon-test:'+k,testerToken);hash.delete('eonTest');history.replaceState(null,'',location.pathname+location.search+(hash.size?'#'+hash.toString():''));}}catch{}
 const post=(action,body)=>fetch('${origin}/api/trigger/'+action,{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),keepalive:action==='events'}).then(r=>r.ok?r.json():null);
 const event=kind=>invite&&post('events',{publicKey:k,invitationToken:invite.invitationToken,event:kind}).catch(()=>{});
 function dismissed(){try{return Date.now()-Number(localStorage.getItem('eon-dismiss:'+k)||0)<config.triggers.cooldownHours*3600000}catch{return false}}
 let config;
 fetch('${origin}/api/widget-config/'+encodeURIComponent(k),{credentials:'omit'}).then(r=>r.json()).then(value=>{config=value;if(!config.enabled||!config.surfaces[surface])return;
 const host=document.createElement('div');host.setAttribute('aria-label','Store negotiation');document.body.append(host);const root=host.attachShadow({mode:'open'});
 const style=document.createElement('style');style.textContent=':host{all:initial;font:14px system-ui;color:#193d31}*{box-sizing:border-box}button{font:inherit;cursor:pointer;border:0;border-radius:10px;padding:12px;background:#214f3d;color:white}.invite{position:fixed;bottom:24px;right:24px;width:290px;max-width:calc(100vw - 32px);padding:20px;background:white;border:1px solid #d8e2d8;box-shadow:0 8px 35px #0002;border-radius:18px;z-index:2147483645}.invite p{line-height:1.5;color:#53645b}.dismiss{float:right;background:transparent;color:#193d31;padding:0 5px}.overlay{position:fixed;inset:0;background:#0008;z-index:2147483646;padding:40px 16px 16px;display:grid;place-items:center}iframe{border:0;border-radius:18px;background:white;width:min(480px,100%);height:min(760px,100%)}.close{position:absolute;right:18px;top:6px}[hidden]{display:none!important}';root.append(style);
 const card=document.createElement('section');card.className='invite';card.hidden=true;card.setAttribute('aria-live','polite');
 const dismiss=document.createElement('button');dismiss.className='dismiss';dismiss.textContent='×';dismiss.setAttribute('aria-label','Dismiss invitation');
 const title=document.createElement('strong'),description=document.createElement('p'),button=document.createElement('button');card.append(dismiss,title,description,button);root.append(card);
 const modal=document.createElement('div');modal.className='overlay';modal.hidden=true;modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','Negotiate with the store');
 const frame=document.createElement('iframe');frame.title='Negotiate an offer';frame.referrerPolicy='no-referrer';const close=document.createElement('button');close.className='close';close.textContent='Close negotiation';modal.append(close,frame);root.append(modal);
 function hide(){closed=true;card.hidden=true;modal.hidden=true;event('dismissed');try{localStorage.setItem('eon-dismiss:'+k,String(Date.now()))}catch{}s.focus?.()}
 dismiss.onclick=hide;close.onclick=hide;modal.onclick=e=>{if(e.target===modal)hide()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)hide()});
 button.onclick=()=>{if(Date.parse(invite.expiresAt)<=Date.now()){card.hidden=true;invite=null;evaluate();return;}frame.src='${origin}/offer/'+encodeURIComponent(k)+'?'+new URLSearchParams({productId:p,variantId:v,currency:c,surface,visitorId:visitor})+'#'+new URLSearchParams({invitationToken:invite.invitationToken});modal.hidden=false;card.hidden=true;close.focus()};
 async function evaluate(){if(closed||pending||invite||dismissed())return;pending=true;try{const result=await post('evaluate',{publicKey:k,productId:p,variantId:v,visitorId:visitor,surface,...(testerToken?{testerToken}:{}),signals:{visits,dwellSeconds:Math.min(3600,Math.floor((Date.now()-started)/1000)),inCart:surface==='cart',checkoutHesitation:surface==='exit_intent'}});if(!result?.eligible)return;invite=result;title.textContent=result.presentation.title;description.textContent=result.presentation.message;button.textContent=result.presentation.button;card.hidden=false;event('shown')}catch{}finally{pending=false}}
 if(surface==='exit_intent')document.addEventListener('mouseleave',e=>{if(e.clientY<=0)evaluate()});else{evaluate();setTimeout(evaluate,config.triggers.minDwellSeconds*1000+100)}
 }).catch(()=>{});})();`;
 return new Response(script,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public, max-age=60','X-Content-Type-Options':'nosniff'}});
}
