"use client";
import {useState} from 'react';
import {houseOfEon} from '../config/house-of-eon.js';
import {simulatePilot} from '../modules/pilot.js';
const steps=['Your store','Choose products','Price boundaries','Allowed extras','When to invite','Try a negotiation','Launch review','Your results'];
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n/100);
const names={price:'Price discount',shipping:'Free shipping',sample:'Free sample',quantity:'Quantity offer',prepaid:'Prepaid offer',credit:'Store credit'};
export default function PilotConsole(){
 const [step,setStep]=useState(0),[products,setProducts]=useState(structuredClone(houseOfEon.products)),[selected,setSelected]=useState(0);
 const [policy,setPolicy]=useState({...houseOfEon.policy}),[trigger,setTrigger]=useState({...houseOfEon.trigger});
 const [platform,setPlatform]=useState('custom'),[message,setMessage]=useState('Can you include shipping?'),[scenario,setScenario]=useState('returning');
 const [result,setResult]=useState(null),[accepted,setAccepted]=useState(false),[runs,setRuns]=useState(0),[notice,setNotice]=useState('');
 const product=products[selected];
 const valid=products.every(p=>p.publicMinor>0&&p.floorMinor>0&&p.costMinor>=0&&p.floorMinor<=p.targetMinor&&p.targetMinor<=p.publicMinor);
 function update(field,value){setProducts(products.map((p,i)=>i===selected?{...p,[field]:Math.round(Number(value)*100)}:p));setResult(null);}
 function run(){setAccepted(false);setNotice('');setResult(simulatePilot({product,policy,trigger,message,
  signals:{stock:product.stock,visits:scenario==='new'?1:4,dwellSeconds:scenario==='new'?10:180,inCart:scenario==='cart',cartMinor:scenario==='cart'?product.publicMinor:0,newLaunch:scenario==='launch'},
  context:{shippingCostMinor:5000,shippingChargeMinor:5000,paymentFeeMinor:0,remainingBudgetMinor:policy.dailyBudgetMinor,round:1,paymentMethod:'prepaid',capabilities:policy.allowed}}));setRuns(runs+1);}
 function download(){const blob=new Blob([JSON.stringify({mode:'sandbox',approvedForProduction:false,store:houseOfEon.domain,platform,products,policy,trigger},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='house-of-eon-sandbox-plan.json';a.click();URL.revokeObjectURL(url);setNotice('Sandbox plan exported. This does not publish store settings.');}
 return <div className="pilot-shell"><aside className="pilot-side"><a href="/pilot" className="pilot-brand">eon<span>NEGOTIATION</span></a><p className="pilot-store">HOUSE OF EON <span>Validation client</span></p><nav aria-label="Setup steps">{steps.map((s,i)=><button key={s} aria-current={i===step?'step':undefined} onClick={()=>setStep(i)}><b>{i+1}</b>{s}</button>)}</nav><div className="pilot-aside-note">A better deal.<br/>Within your boundaries.<p>Start small. Prove value here before expanding.</p></div></aside>
 <main className="pilot-main"><header className="pilot-top"><span>Merchant studio / House of EON</span><span className="pilot-badge">Sandbox · no live changes</span></header>
 <div className="pilot-heading"><div><p className="pilot-eyebrow">STEP {step+1} OF 8 · {['EON CONNECT','EON CONNECT','EON RULES','EON RULES','EON TRIGGER','EON CONVERSE','EON CONNECT','EON OPTIMIZE'][step]}</p><h1>{steps[step]}</h1><p>{['Give interested shoppers a reason to complete their purchase.','Start with two products you can learn from.','You set the boundaries. Every offer stays inside them.','A useful offer can be more than a lower price.','Invite shoppers when they need help deciding.','See the customer experience before switching anything on.','A controlled pilot starts with verified checkout and approved rules.','Paid orders prove value. Accepted offers are only the beginning.'][step]}</p></div><button className="pilot-secondary" onClick={download}>Export sandbox plan ↗</button></div>
 <div className="pilot-note">This studio uses fictional, editable prices. Settings stay in this page until you export them. No real customer or store data is connected.</div>
 {step===0&&<section className="pilot-panel"><h2>Connect your store</h2><p>House of EON · houseofeon.in</p><div className="pilot-options">{[['custom','Custom website','Use your existing checkout and product catalog.'],['shopify','Shopify','Use the same rules with a Shopify store connection.']].map(([id,title,desc])=><button key={id} aria-pressed={platform===id} className={platform===id?'chosen':''} onClick={()=>setPlatform(id)}><h3>{title}</h3><p>{desc}</p><strong>{platform===id?'Selected for planning':'Choose platform'} →</strong></button>)}</div><p className="pilot-muted">Planning selection only. Complete the authenticated store connection in the existing dashboard before launch.</p><a className="pilot-link" href="/dashboard">Open store connections →</a></section>}
 {step===1&&<section className="pilot-panel"><h2>Your first test products</h2><p>Both products are included in this sandbox. Production SKU mappings still need confirmation.</p>{products.map((p,i)=><button className={'pilot-product '+(selected===i?'selected':'')} key={p.sku} onClick={()=>{setSelected(i);setResult(null);}}><span className="pilot-product-art">{i===0?'AW':'TP'}</span><span><strong>{p.name}</strong><small>{p.sku} · Sample SKU</small></span><strong>{money(p.publicMinor)}</strong><span>Edit →</span></button>)}</section>}
 {step===2&&<section className="pilot-panel"><h2>Protect every sale</h2><label>Product<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{products.map((p,i)=><option value={i} key={p.sku}>{p.name}</option>)}</select></label><div className="pilot-grid">{[['publicMinor','Public price','The same listed price for everyone.'],['targetMinor','Preferred price','Where you would like negotiation to land.'],['floorMinor','Absolute minimum','Protected after extras, fees and shipping subsidy.'],['costMinor','Product cost','Used to check contribution after approved extras.']].map(([key,title,help])=><label key={key}>{title} · INR<input type="number" min="0" step="0.01" value={product[key]/100} onChange={e=>update(key,e.target.value)}/><small>{help}</small></label>)}</div><label>Strategy<select value={policy.strategy} onChange={e=>{setPolicy({...policy,strategy:e.target.value});setResult(null);}}><option value="protect_margin">Protect Margin</option><option value="balanced">Balanced</option><option value="maximize_conversion">Maximize Conversion</option><option value="clear_inventory">Clear Inventory</option></select></label>{!valid&&<p role="alert">Enter positive prices with minimum ≤ preferred ≤ public price.</p>}<details><summary>Advanced boundaries</summary><p>Sandbox defaults: maximum 12% item discount, 3 rounds, 15-minute expiry, INR 2,000 daily concession budget and INR 100 minimum order contribution. Live publishing must confirm tax and cost basis.</p></details></section>}
 {step===3&&<section className="pilot-panel"><h2>What may EON offer?</h2><p>Extras are available only when the store can enforce them at checkout.</p><div className="pilot-grid">{Object.entries(names).map(([key,label])=><label className="pilot-check" key={key}><input type="checkbox" checked={policy.allowed.includes(key)} onChange={e=>{setPolicy({...policy,allowed:e.target.checked?[...policy.allowed,key]:policy.allowed.filter(t=>t!==key)});setResult(null);}}/><span><strong>{label}</strong><small>{key==='credit'?'Credit face value counts against your budget.':key==='prepaid'?'Requires prepaid payment at checkout.':'Every extra is checked against your minimum.'}</small></span></label>)}</div><details><summary>How sandbox costs work</summary><p>Shipping costs INR 50; sample costs INR 15; credit is INR 10. These are test assumptions, not House of EON commercial terms. Approved custom terms and COD pricing need validated connector capabilities.</p></details></section>}
 {step===4&&<section className="pilot-panel"><h2>Offer help at the right moment</h2><div className="pilot-grid"><label>After this many visits<input type="number" min="2" max="20" value={trigger.minVisits} onChange={e=>setTrigger({...trigger,minVisits:Math.max(2,Number(e.target.value))})}/></label><label>After seconds of consideration<input type="number" min="30" value={trigger.minDwellSeconds} onChange={e=>setTrigger({...trigger,minDwellSeconds:Math.max(30,Number(e.target.value))})}/></label></div><label className="pilot-check"><input type="checkbox" checked={trigger.excludeNewLaunch} onChange={e=>setTrigger({...trigger,excludeNewLaunch:e.target.checked})}/>Protect new launches</label><p>First-time visitors receive no automatic discount invitation. Low stock, purchase completion, cooldowns and control-group assignment suppress invitations.</p><details><summary>More invitation options</summary><p>Cart thresholds, checkout hesitation, consented recovery, approved campaigns and returning-customer cart activity are defined in EON Trigger. Dwell and visits are hints; server-verified stock, costs and policy always control offers.</p></details></section>}
 {step===5&&<div className="pilot-preview-grid"><section className="pilot-panel"><h2>Set the scene</h2><label>Test product<select value={selected} onChange={e=>{setSelected(Number(e.target.value));setResult(null);}}>{products.map((p,i)=><option key={p.sku} value={i}>{p.name}</option>)}</select></label><label>Customer situation<select value={scenario} onChange={e=>{setScenario(e.target.value);setResult(null);}}><option value="returning">Viewed four times · considering for 3 minutes</option><option value="new">First visit · just arrived</option><option value="cart">Returning visitor · product in cart</option><option value="launch">New launch · protected product</option></select></label><p>Try “under 900”, “include shipping” or “I’ll buy two for a better price”.</p><p className="pilot-muted">Offline intent preview. Production AI and checkout are not called.</p></section><section className="pilot-chat"><div className="pilot-chat-header"><span>EON Converse</span><span>Preview</span></div><h2>{product.name}</h2><p>{money(product.publicMinor)} · sample public price</p><label htmlFor="pilot-request">Customer request</label><textarea id="pilot-request" value={message} maxLength={1000} onChange={e=>{setMessage(e.target.value);setResult(null);}}/><button className="pilot-primary" disabled={!valid||!message.trim()} onClick={run}>Test this negotiation →</button>{result&&<div aria-live="polite" className="pilot-reply"><small>{result.eligible.state.replaceAll('_',' ')}</small><p>{result.message}</p>{result.offer&&<><h2>{money(result.offer.totalMinor)}</h2><p>{names[result.offer.type]} · includes {money(result.offer.shippingMinor)} shipping · {result.intent.quantity} item(s)</p><small>Expires {new Date(result.offer.expiresAt).toLocaleTimeString()} · sample tax-inclusive scenario</small><button className="pilot-secondary" disabled={accepted||Date.parse(result.offer.expiresAt)<=Date.now()} onClick={()=>{if(Date.parse(result.offer.expiresAt)<=Date.now()){setNotice('This test offer expired. Run a new negotiation.');return;}setAccepted(true);}}> {accepted?'Sandbox acceptance recorded':'Simulate accepting offer'}</button>{accepted&&<p>Next in production: verify the cart, reserve the deal once, and open the merchant checkout. This preview creates no checkout link.</p>}</>}</div>}</section></div>}
 {step===6&&<section className="pilot-panel"><h2>Ready for a real pilot?</h2><p>Sandbox checks help you prepare. They do not verify production readiness.</p>{['Confirm actual SKU prices, floors and commercial costs','Connect the store and verify ownership','Test every enabled concession at checkout','Complete a staging payment and verify its order event','Configure recovery consent, limits and pause controls','Approve a small treatment cohort and control group'].map(t=><div className="pilot-gate" key={t}><span>○</span>{t}<small>Required</small></div>)}<button disabled className="pilot-primary">Live activation unavailable in sandbox</button><p className="pilot-muted">Continue in the authenticated console after all rollout gates pass.</p></section>}
 {step===7&&<><div className="pilot-metrics">{[['Negotiations started','—'],['Verified paid orders','—'],['Attributed revenue','—'],['Conversion lift','Not measured']].map(([title,value])=><section className="pilot-panel" key={title}><small>{title}</small><h2>{value}</h2><p>Awaiting live pilot data</p></section>)}</div><section className="pilot-panel"><h2>Learn what creates profitable orders</h2><div className="pilot-grid"><div><h3>Negotiation funnel</h3><p>Eligible → invited → started → accepted → checkout → paid → refunded</p><p>{runs} local simulations · excluded from live reporting</p></div><div><h3>Your first success check</h3><p>Can House of EON set up, test, launch, pause and understand results without technical help?</p></div></div><p>Best deal type, average concession, recovered revenue and contribution lift appear after verified orders. Coupon comparisons are modeled estimates until tested against a real coupon cohort.</p><span className="pilot-badge">EON Optimize · collecting data</span></section></>}
 {notice&&<p role="status">{notice}</p>}<footer className="pilot-footer"><button className="pilot-secondary" disabled={step===0} onClick={()=>setStep(step-1)}>← Back</button><span>{step+1} / 8</span><button className="pilot-primary" disabled={step===7||(step===2&&!valid)} onClick={()=>setStep(step+1)}>{step===4?'Preview negotiation':'Continue'} →</button></footer></main></div>;
}
