"use client";
import {useEffect,useMemo,useState} from "react";
import {backendEnvironment,connectorDiagnostic,connectorReadiness,shouldRefreshWorkspace} from "../lib/connector-ui.js";

const formatTime=value=>value?new Date(value).toLocaleString():"Not yet";

export default function StoreConnection({workspace,products=[],onWorkspaceChanged}) {
  const defaultEndpoint=`https://api.${workspace.domain}/negotiation/v3`;
  const [state,setState]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[endpoint,setEndpoint]=useState(defaultEndpoint),[endpointDirty,setEndpointDirty]=useState(false),[setup,setSetup]=useState(null),[copied,setCopied]=useState(""),[shop,setShop]=useState(""),[selected,setSelected]=useState(""),[shipping,setShipping]=useState({});
  async function api(body){const response=await fetch(`/api/platform/workspaces/${workspace.id}/installation`,{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:{},body:body?JSON.stringify(body):undefined,cache:"no-store"}),value=await response.json();if(!response.ok)throw Error(value.error||"Connection request failed.");return value;}
  async function reload(){const value=await api();setState(value);return value;}
  useEffect(()=>{let active=true;api().then(value=>{if(!active)return;setState(value);const custom=value.installations.find(item=>item.provider==="custom");setEndpoint(custom?.endpoint||defaultEndpoint);setEndpointDirty(false);}).catch(e=>active&&setError(e.message));return()=>{active=false};},[workspace.id,defaultEndpoint]);
  async function run(body,{message,followup}={}){setBusy(true);setError("");setNotice("");try{let result=await api(body);if(result.setupSecret)setSetup({workspaceId:workspace.id,installationId:result.id,secret:result.setupSecret});if(followup)result=await api({...followup,installationId:result.id});const latest=await reload();if(body.action==="update_custom_endpoint"){setEndpointDirty(false);setEndpoint(latest.installations.find(item=>item.id===body.installationId)?.endpoint||body.endpoint);}if(shouldRefreshWorkspace(body.action)||shouldRefreshWorkspace(followup?.action))await onWorkspaceChanged?.();if(result.error)setError(connectorDiagnostic(result.error));else if(body.action==="sync")setNotice(`${result.imported} imported, ${result.updated} updated. Catalog refreshed ${formatTime(result.lastSyncAt)}.`);else if(message)setNotice(message);return result;}catch(e){setError(e.message.startsWith("CONNECTOR_")?connectorDiagnostic(e.message):e.message);}finally{setBusy(false);}}
  async function checkAndSync(item){setBusy(true);setError("");setNotice("");try{const checked=await api({action:"test",installationId:item.id});if(checked.error){await reload();return setError(connectorDiagnostic(checked.error));}if(checked.result?.capabilities?.catalog){const synced=await api({action:"sync",installationId:item.id});await onWorkspaceChanged?.();setNotice(`Connection checked. ${synced.imported} imported and ${synced.updated} updated.`);}else setNotice("Capabilities checked. This endpoint does not provide a catalog.");await reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function copy(label,value){try{await navigator.clipboard.writeText(value);setCopied(label);setTimeout(()=>setCopied(""),2000);}catch{setError("Copy was blocked by the browser. Select the value and copy it manually.");}}
  const custom=state?.installations.find(item=>item.provider==="custom");
  const linked=products.filter(p=>p.externalVariantId),product=linked.find(p=>p.id===selected)||linked[0];
  const money=n=>new Intl.NumberFormat("en",{style:"currency",currency:workspace.currency}).format((n||0)/100),toMinor=value=>{const n=Number(value);if(!Number.isFinite(n)||n<0)throw Error("Enter a valid shipping amount.");return Math.round(n*100);};
  const platformOrigin=typeof window==="undefined"?"https://eon-negotiation.vercel.app":window.location.origin;
  const setupText=useMemo(()=>setup?backendEnvironment(setup.workspaceId,setup.installationId,setup.secret):"",[setup]);
  return <section className="panel" style={{padding:28,marginBottom:24}} aria-label="Live commerce connections">
    <div className="section-head"><div><span className="eyebrow">COMMERCE CONNECTION</span><h2>Connect {workspace.name}</h2><p>Connect the catalog first. Live negotiation unlocks only after exact-cart economics and enforceable checkout pass.</p></div><span className="pill green">Contract v3</span></div>
    {error&&<p className="notice error" role="alert">{error}</p>}
    {notice&&<p className="notice" role="status">{notice}</p>}
    {!state?<p>Loading connections…</p>:<>
      <div className="notice"><div><strong>{state.domainVerified?"Company domain verified":"Verify company domain"}</strong>{!state.domainVerified&&<><p>Create a TXT record. Many DNS providers want the host-only name; the full hostname is shown for providers that require it.</p><div className="setting-row"><span>Host/name</span><code>{state.domainVerificationHost}</code><button className="text-button" onClick={()=>copy("dns-host",state.domainVerificationHost)}>{copied==="dns-host"?"Copied":"Copy"}</button></div><div className="setting-row"><span>Full hostname</span><code>{state.domainVerificationFqdn}</code><button className="text-button" onClick={()=>copy("dns-fqdn",state.domainVerificationFqdn)}>{copied==="dns-fqdn"?"Copied":"Copy"}</button></div><div className="setting-row"><span>TXT value</span><code>{state.domainVerificationRecord}</code><button className="text-button" onClick={()=>copy("dns-value",state.domainVerificationRecord)}>{copied==="dns-value"?"Copied":"Copy"}</button></div><div><button className="secondary" disabled={busy} onClick={()=>run({action:"verify_domain"},{message:"Company domain verified."})}>Check DNS record</button></div></>}</div></div>
      <div className="rules-grid">
        <form className="panel inset" onSubmit={e=>{e.preventDefault();if(custom)run({action:"update_custom_endpoint",installationId:custom.id,endpoint},{message:"Endpoint saved and capabilities checked again.",followup:{action:"test"}});else run({action:"configure_custom",endpoint},{message:"Connection created. Give the one-time backend settings to the merchant developer."});}}>
          <h3>Custom store</h3><p>For a custom backend, Supabase, services or B2B. The merchant developer adds one scoped endpoint; database credentials stay with the merchant.</p>
          <label>HTTPS endpoint<input value={endpoint} onChange={e=>{setEndpoint(e.target.value);setEndpointDirty(true);}} required/></label>
          {custom&&<p className="fine">Saved endpoint: <code>{custom.endpoint}</code>{endpointDirty?" · Unsaved changes":""}</p>}
          <button className="primary" disabled={busy||(custom&&!endpointDirty)}>{custom?"Save endpoint":"Create custom connection"}</button>
          {custom&&<button type="button" className="secondary" disabled={busy} onClick={()=>run({action:"rotate_custom_secret",installationId:custom.id},{message:"Secret rotated. Update the merchant backend before checking capabilities."})}>Rotate installation secret</button>}
          <p className="fine">Saving an endpoint never rotates its secret. Rotation revokes the previous secret and returns a replacement once.</p>
          {setup&&<div className="notice"><div><strong>Copy these server-side values now</strong><p>Send this block to the merchant developer through a secure channel. It is shown only after creation or explicit rotation. Use one secret variable only; never place it in browser code.</p><pre><code>{setupText}</code></pre><button type="button" className="secondary" onClick={()=>copy("setup",setupText)}>{copied==="setup"?"Copied":"Copy backend settings"}</button></div></div>}
        </form>
        <form className="panel inset" onSubmit={e=>{e.preventDefault();window.location.assign(`/api/integrations/shopify/start?workspaceId=${encodeURIComponent(workspace.id)}&shop=${encodeURIComponent(shop)}`);}}><h3>Shopify</h3><p>OAuth grants scoped access to products, inventory and negotiated draft-order checkout.</p><label>.myshopify.com domain<input value={shop} onChange={e=>setShop(e.target.value)} placeholder="your-store.myshopify.com" required/></label><button className="primary" disabled={busy||!state.shopifyConfigured}>{state.shopifyConfigured?"Install Shopify app":"Shopify app credentials required"}</button></form>
      </div>
      {!state.installations.length&&<div className="notice"><strong>No store connected.</strong><span>Choose a platform. A custom store needs a one-time developer installation before catalog sync.</span></div>}
      {state.installations.map(item=>{const readiness=connectorReadiness(item),canTestCart=readiness.negotiationReady;return <div className="panel inset" key={item.id} style={{marginTop:20}}>
        <div className="section-head"><div><span className="eyebrow">{item.provider.toUpperCase()}</span><h3>{item.shopDomain||item.endpoint}</h3><p>{readiness.negotiationReady?"Negotiation ready":readiness.catalog?"Catalog connected · negotiation setup incomplete":"Connection setup incomplete"} · Mode: {item.activationStatus}</p></div><span className={`pill ${readiness.negotiationReady?"green":"amber"}`}>{readiness.negotiationReady?"ready":"read only"}</span></div>
        {item.error&&<p className="notice error">{connectorDiagnostic(item.error)}</p>}
        <div className="data-line"><span>Catalog</span><small>{readiness.catalog?"Available":"Missing"}</small></div>
        <div className="data-line"><span>Inventory</span><small>{readiness.inventory?"Synchronized snapshot":"Missing"}</small></div>
        <div className="data-line"><span>Checkout enforcement</span><small>{readiness.checkout?"Declared":"Not implemented"}</small></div>
        <div className="data-line"><span>Reconciliation and events</span><small>{readiness.reconciliation&&readiness.events?"Declared":"Not implemented"}</small></div>
        {item.lastSyncAt&&<p className="fine">Last catalog sync: {formatTime(item.lastSyncAt)}{item.config?.catalogSync&&` · ${item.config.catalogSync.imported} imported, ${item.config.catalogSync.updated} updated`}</p>}
        {!readiness.negotiationReady&&readiness.catalog&&<div className="notice"><div><strong>Catalog connected; customer negotiation remains off.</strong><p>The merchant developer still needs: {readiness.missing.join(", ")}.</p></div></div>}
        <div className="button-row"><button className="secondary" disabled={busy} onClick={()=>checkAndSync(item)}>Check capabilities & sync</button>{readiness.catalog&&<button className="secondary" disabled={busy} onClick={()=>run({action:"sync",installationId:item.id})}>Sync catalog now</button>}{item.activationStatus==="active"?<button className="secondary" disabled={busy} onClick={()=>run({action:"pause",installationId:item.id},{message:"Connection paused."})}>Pause</button>:item.status==="ready"?<button className="secondary" disabled={busy} onClick={()=>run({action:"activate",installationId:item.id},{message:"Connection activated."})}>Activate</button>:<button className="secondary" disabled title="Complete live-cart and checkout verification first">Activation locked</button>}</div>
        {canTestCart&&linked.length>0?<><h4>Verify a real cart</h4><div className="form-grid"><label>Product<select value={product?.id||""} onChange={e=>setSelected(e.target.value)}>{linked.map(p=><option value={p.id} key={p.id}>{p.name} · {money(p.priceMinor)}</option>)}</select></label><label>Postal code<input id={`postal-${item.id}`} placeholder="600001"/></label></div><button className="primary" disabled={busy||!product} onClick={()=>{const postal=document.getElementById(`postal-${item.id}`).value.trim();run({action:"test",installationId:item.id,cart:{currency:workspace.currency,lines:[{productId:product.externalProductId,variantId:product.externalVariantId,quantity:1}],promotionCodes:[],paymentMethod:"prepaid",destination:postal?{country:"IN",postalCode:postal}:null}},{message:"Fresh cart economics and checkout support verified."});}}>Verify price, stock and checkout</button></>:readiness.catalog&&<p className="fine">Real-cart testing will appear after the connector declares all required negotiation and checkout capabilities.</p>}
        {item.provider==="shopify"&&<><h4>Shipping assumption for Shopify</h4><p className="fine">Use merchant-approved amounts until a carrier quote adapter is connected. Leave country blank to allow all destinations.</p><div className="form-grid"><label>Country code<input value={shipping[item.id]?.country||""} maxLength={2} placeholder="IN" onChange={e=>setShipping(v=>({...v,[item.id]:{...v[item.id],country:e.target.value.toUpperCase()}}))}/></label><label>Merchant cost ({workspace.currency})<input type="number" min="0" step="0.01" value={shipping[item.id]?.cost||""} onChange={e=>setShipping(v=>({...v,[item.id]:{...v[item.id],cost:e.target.value}}))}/></label><label>Customer charge ({workspace.currency})<input type="number" min="0" step="0.01" value={shipping[item.id]?.charge||""} onChange={e=>setShipping(v=>({...v,[item.id]:{...v[item.id],charge:e.target.value}}))}/></label></div><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>run({action:"shipping",installationId:item.id,mode:"none",merchantCostMinor:0,customerChargeMinor:0,countries:[]})}>No shipping</button><button className="secondary" disabled={busy} onClick={()=>{try{const draft=shipping[item.id]||{},country=(draft.country||"").trim();if(country&&!/^[A-Z]{2}$/.test(country))throw Error("Use a two-letter country code.");run({action:"shipping",installationId:item.id,mode:"flat",merchantCostMinor:toMinor(draft.cost||0),customerChargeMinor:toMinor(draft.charge||0),countries:country?[country]:[]});}catch(e){setError(e.message);}}}>Save flat shipping</button></div></>}
        {item.publicKey&&<div className="notice"><div><strong>Customer widget test is ready</strong><p>The snippet uses the selected synchronized product. Production activation still requires verified domain ownership.</p><code>{`<script src="${platformOrigin}/widget.js" data-workspace="${item.publicKey}" data-product="${product?.externalProductId||"PRODUCT_ID"}" data-variant="${product?.externalVariantId||"VARIANT_ID"}" data-currency="${workspace.currency}"></script>`}</code></div></div>}
      </div>;})}
    </>}
  </section>;
}
