"use client";
import {useEffect,useState} from "react";

export default function StoreConnection({workspace,products=[]}) {
  const [state,setState]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[endpoint,setEndpoint]=useState(`https://api.${workspace.domain}/negotiation/v3`),[setup,setSetup]=useState(null),[shop,setShop]=useState(""),[selected,setSelected]=useState(""),[shipping,setShipping]=useState({});
  async function api(body){const response=await fetch(`/api/platform/workspaces/${workspace.id}/installation`,{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:{},body:body?JSON.stringify(body):undefined,cache:"no-store"}),value=await response.json();if(!response.ok)throw Error(value.error||"Connection request failed.");return value;}
  async function reload(){setState(await api());}
  useEffect(()=>{let active=true;api().then(v=>active&&setState(v)).catch(e=>active&&setError(e.message));return()=>{active=false};},[workspace.id]);
  async function run(body){setBusy(true);setError("");try{const result=await api(body);if(result.setupSecret)setSetup({installationId:result.id,secret:result.setupSecret});await reload();return result;}catch(e){setError(e.message);}finally{setBusy(false);}}
  const linked=products.filter(p=>p.externalVariantId),product=linked.find(p=>p.id===selected)||linked[0];
  const money=n=>new Intl.NumberFormat("en",{style:"currency",currency:workspace.currency}).format((n||0)/100),toMinor=value=>{const n=Number(value);if(!Number.isFinite(n)||n<0)throw Error("Enter a valid shipping amount.");return Math.round(n*100);};
  const platformOrigin=typeof window==="undefined"?"https://eon-negotiation.vercel.app":window.location.origin;
  return <section className="panel" style={{padding:28,marginBottom:24}} aria-label="Live commerce connections">
    <div className="section-head"><div><span className="eyebrow">LIVE COMMERCE</span><h2>Connect {workspace.name}</h2><p>Custom stores and Shopify use the same catalog, context, pricing and checkout contract.</p></div><span className="pill green">Contract v3</span></div>
    {error&&<p className="notice error" role="alert">{error}</p>}
    {!state?<p>Loading connections…</p>:<>
      <div className="notice"><div><strong>{state.domainVerified?"Company domain verified":"Verify company domain"}</strong>{!state.domainVerified&&<><p>Add this TXT record at <code>_eon-negotiation.{state.workspaceDomain}</code>:</p><code>{state.domainVerificationRecord}</code><div><button className="secondary" disabled={busy} onClick={()=>run({action:"verify_domain"})}>Check DNS record</button></div></>}</div></div>
      <div className="rules-grid">
        <form className="panel inset" onSubmit={e=>{e.preventDefault();run({action:"configure_custom",endpoint});}}><h3>Custom store endpoint</h3><p>For Supabase, custom code, digital products, services or B2B. Your server keeps its database credentials.</p><label>HTTPS endpoint<input value={endpoint} onChange={e=>setEndpoint(e.target.value)} required/></label><button className="primary" disabled={busy}>Generate installation secret</button>{setup&&<div className="notice"><div><strong>Copy these backend values now</strong><p>Store them only in the merchant backend environment. Regenerating the connection replaces the secret.</p><code>{`NEGOTIATION_INSTALLATION_ID=${setup.installationId}\nNEGOTIATION_CONNECTOR_SECRET=${setup.secret}`}</code></div></div>}</form>
        <form className="panel inset" onSubmit={e=>{e.preventDefault();window.location.assign(`/api/integrations/shopify/start?workspaceId=${encodeURIComponent(workspace.id)}&shop=${encodeURIComponent(shop)}`);}}><h3>Shopify</h3><p>OAuth grants scoped access to products, inventory and negotiated draft-order checkout.</p><label>.myshopify.com domain<input value={shop} onChange={e=>setShop(e.target.value)} placeholder="your-store.myshopify.com" required/></label><button className="primary" disabled={busy||!state.shopifyConfigured}>{state.shopifyConfigured?"Install Shopify app":"Shopify app credentials required"}</button></form>
      </div>
      {!state.installations.length&&<div className="notice"><strong>No live store connected.</strong><span>Configure one custom endpoint or install the Shopify app.</span></div>}
      {state.installations.map(item=><div className="panel inset" key={item.id} style={{marginTop:20}}>
        <div className="section-head"><div><span className="eyebrow">{item.provider.toUpperCase()}</span><h3>{item.shopDomain||item.endpoint}</h3><p>Status: {item.status.replaceAll("_"," ")} · Mode: {item.activationStatus}</p></div><span className={`pill ${item.status==="ready"?"green":"amber"}`}>{item.status}</span></div>
        {item.error&&<p className="notice error">{item.error}</p>}
        <div className="button-row"><button className="secondary" disabled={busy} onClick={()=>run({action:"test",installationId:item.id})}>Check capabilities</button><button className="secondary" disabled={busy} onClick={()=>run({action:"sync",installationId:item.id})}>Sync catalog</button>{item.activationStatus==="paused"?<button className="secondary" disabled={busy} onClick={()=>run({action:"activate",installationId:item.id})}>Activate</button>:<button className="secondary" disabled={busy} onClick={()=>run({action:"pause",installationId:item.id})}>Pause</button>}</div>
        {linked.length>0&&<><h4>Verify a real cart</h4><div className="form-grid"><label>Product<select value={product?.id||""} onChange={e=>setSelected(e.target.value)}>{linked.map(p=><option value={p.id} key={p.id}>{p.name} · {money(p.priceMinor)}</option>)}</select></label><label>Postal code<input id={`postal-${item.id}`} placeholder="600001"/></label></div><button className="primary" disabled={busy||!product} onClick={()=>{const postal=document.getElementById(`postal-${item.id}`).value.trim();run({action:"test",installationId:item.id,cart:{currency:workspace.currency,lines:[{productId:product.externalProductId,variantId:product.externalVariantId,quantity:1}],promotionCodes:[],paymentMethod:"prepaid",destination:postal?{country:"IN",postalCode:postal}:null}})}}>Verify price, stock and checkout</button></>}
        <h4>Shipping assumption for native adapters</h4><p className="fine">Custom endpoints return their own live shipping facts. Shopify can use merchant-approved amounts until a carrier quote adapter is connected. Leave country blank to allow all destinations.</p><div className="form-grid"><label>Country code<input value={shipping[item.id]?.country||""} maxLength={2} placeholder="IN" onChange={e=>setShipping(v=>({...v,[item.id]:{...v[item.id],country:e.target.value.toUpperCase()}}))}/></label><label>Merchant cost ({workspace.currency})<input type="number" min="0" step="0.01" value={shipping[item.id]?.cost||""} onChange={e=>setShipping(v=>({...v,[item.id]:{...v[item.id],cost:e.target.value}}))}/></label><label>Customer charge ({workspace.currency})<input type="number" min="0" step="0.01" value={shipping[item.id]?.charge||""} onChange={e=>setShipping(v=>({...v,[item.id]:{...v[item.id],charge:e.target.value}}))}/></label></div><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>run({action:"shipping",installationId:item.id,mode:"none",merchantCostMinor:0,customerChargeMinor:0,countries:[]})}>No shipping</button><button className="secondary" disabled={busy} onClick={()=>{try{const draft=shipping[item.id]||{},country=(draft.country||"").trim();if(country&&!/^[A-Z]{2}$/.test(country))throw Error("Use a two-letter country code.");run({action:"shipping",installationId:item.id,mode:"flat",merchantCostMinor:toMinor(draft.cost||0),customerChargeMinor:toMinor(draft.charge||0),countries:country?[country]:[]});}catch(e){setError(e.message);}}}>Save flat shipping</button></div>
        {item.publicKey&&<div className="notice"><div><strong>Customer widget test is ready</strong><p>The snippet uses the selected synchronized product. Production activation still requires verified domain ownership.</p><code>{`<script src="${platformOrigin}/widget.js" data-workspace="${item.publicKey}" data-product="${product?.externalProductId||"PRODUCT_ID"}" data-variant="${product?.externalVariantId||"VARIANT_ID"}" data-currency="${workspace.currency}"></script>`}</code></div></div>}
      </div>)}
    </>}
  </section>;
}
