export const connectors = [
  {
    id: "manual",
    name: "Manual catalog",
    category: "Catalog",
    mark: "↥",
    color: "olive",
    stage: "available",
    label: "Available now",
    description:
      "Add products yourself or import a CSV. Start testing without a store integration.",
    data: ["Catalog", "Price floors", "Stock snapshots"],
    method: "Validated CSV or product form",
    next: "Import a catalog in Products. Values are merchant-entered snapshots, not live inventory.",
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "Commerce",
    mark: "S",
    color: "green",
    stage: "available",
    label: "OAuth ready",
    description:
      "Install with Shopify OAuth, sync variants and inventory, and create merchant-approved draft-order checkouts.",
    data: ["Catalog", "Inventory", "Checkout", "Webhooks"],
    method: "Merchant-approved Shopify app installation",
    next: "Add Shopify app credentials and the exact callback URL, then install on a development store before inviting a merchant.",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    category: "Commerce",
    mark: "W",
    color: "purple",
    stage: "planned",
    label: "Planned",
    description:
      "Connect a WordPress store with scoped REST API credentials and signed webhooks.",
    data: ["Catalog", "Inventory", "Orders"],
    method: "WooCommerce application authorization / scoped API keys",
    next: "Build the REST adapter and webhook verification. Begin with read access; request write access only for verified checkout integration.",
  },
  {
    id: "bigcommerce",
    name: "BigCommerce",
    category: "Commerce",
    mark: "B",
    color: "navy",
    stage: "planned",
    label: "Planned",
    description:
      "A commerce adapter for storefront catalog, inventory and order events.",
    data: ["Catalog", "Inventory", "Orders"],
    method: "BigCommerce app authorization",
    next: "Validate app scopes and checkout discount enforcement on a sandbox store before publishing this adapter.",
  },
  {
    id: "custom",
    name: "Custom API",
    category: "Commerce",
    mark: "{ }",
    color: "blue",
    stage: "available",
    label: "Endpoint ready",
    description:
      "Bring any backend: custom stores, digital products, services or B2B price lists.",
    data: ["Catalog", "Availability", "Economics", "Quote handoff"],
    method: "Versioned HTTPS API with per-installation authentication",
    next: "Deploy the v3 reference handler on your company domain, then run capability, catalog, cart and checkout-readiness checks.",
  },
  {
    id: "supabase",
    name: "Supabase / Postgres",
    category: "Data",
    mark: "ϟ",
    color: "green",
    stage: "contract",
    label: "Via custom API",
    description:
      "Keep your current database. Expose only approved business facts through your backend.",
    data: ["Stock summaries", "Sales aggregates", "Costs"],
    method: "Merchant-owned API adapter; no master DB password",
    next: "Map your backend to the Custom API contract. House of EON is our first reference client, not a special platform dependency.",
  },
  {
    id: "shipping",
    name: "Shipping providers",
    category: "Shipping",
    mark: "↗",
    color: "orange",
    stage: "planned",
    label: "Planned",
    description:
      "Delivery costs and serviceability from Delhivery, Shiprocket or your existing carrier.",
    data: ["Serviceability", "Freight quotes", "Quote expiry"],
    method: "Merchant backend quote or approved rate card",
    next: "Validate origin, package dimensions, destination and payment method. A serviceable postcode alone does not establish freight cost.",
  },
  {
    id: "payments",
    name: "Payment providers",
    category: "Payments",
    mark: "↔",
    color: "blue",
    stage: "planned",
    label: "Via store checkout",
    description:
      "Reconcile paid and refunded offers through the merchant’s Stripe or Razorpay integration.",
    data: ["Paid orders", "Refunds", "Fees"],
    method: "Verified store payment events",
    next: "Keep payments in the merchant checkout. Never trust a browser payment-success message; verify order/amount/currency and deduplicate events.",
  },
  {
    id: "erp",
    name: "ERP & CRM",
    category: "Data",
    mark: "▤",
    color: "purple",
    stage: "planned",
    label: "Later",
    description:
      "Enrich decisions with approved stock, costs and loyalty eligibility from business systems.",
    data: ["Costs", "Warehouses", "Loyalty eligibility"],
    method: "Scoped adapter through the same data contract",
    next: "Prioritize specific providers after commerce onboarding works. CRM access is optional; no full customer database is required.",
  },
];
export const defaults = {
  maxDiscountBps: 1000,
  rounds: 3,
  ttlMinutes: 15,
  dailyBudgetMinor: 100000,
  lowStockThreshold: 3,
  lowStockDiscountBps: 200,
  excessStockThreshold: 30,
  historyEnabled: false,
};
export const currencies = ["INR", "USD", "AED", "EUR", "GBP", "SGD"];
